# Data structures

##### source: https://docs.python.org/3/tutorial/datastructures.html#

This chapter describes some things you’ve learned about already in more detail, and adds some new things as well.

## 1. The list data type has some more methods. Here are all of the methods of list objects:

#### list.append(x)

    Add an item to the end of the list. Equivalent to a[len(a):] = [x].

#### list.extend(iterable)

    Extend the list by appending all the items from the iterable. Equivalent to a[len(a):] = iterable.

#### list.insert(i, x)

    Insert an item at a given position. The first argument is the index of the element before which to insert, 
    so a.insert(0, x) inserts at the front of the list, and a.insert(len(a), x) is equivalent to a.append(x).

#### list.remove(x)

    Remove the first item from the list whose value is equal to x. It raises a ValueError if there is no such item.

#### list.pop([i])

    Remove the item at the given position in the list, and return it. If no index is specified, a.pop() removes 
    and returns the last item in the list. (The square brackets around the i in the method signature denote that 
    the parameter is optional, not that you should type square brackets at that position. You will see this 
    notation frequently in the Python Library Reference.)

#### list.clear()

    Remove all items from the list. Equivalent to del a[:].

#### list.index(x[, start[, end]])

    Return zero-based index in the list of the first item whose value is equal to x. Raises a ValueError if there 
    is no such item.

    The optional arguments start and end are interpreted as in the slice notation and are used to limit the 
    search to a particular subsequence of the list. The returned index is computed relative to the beginning of 
    the full sequence rather than the start argument.

#### list.count(x)

    Return the number of times x appears in the list.

#### list.sort(*, key=None, reverse=False)

    Sort the items of the list in place (the arguments can be used for sort customization, see sorted() for 
    their explanation).

#### list.reverse()

    Reverse the elements of the list in place.

#### list.copy()

    Return a shallow copy of the list. Equivalent to a[:].

## 2. Here are presented examples that uses most of the list methods:

In [2]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
fruits.count('apple')  # count how many times you find the word 'apple' in the list 

2

In [3]:
fruits.index('banana')   # Find the first banana in the list

3

In [4]:
fruits.index('banana', 4)  # Find next banana starting a position 4

6

In [5]:
fruits.reverse()   # it is the same as fruits[::-1]
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']

In [6]:
fruits.append('grape')     # append the word 'grape' at the end of the list
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange', 'grape']

In [8]:
fruits.sort()  # sort the list in alphabetical order
fruits

['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange', 'pear']

In [9]:
fruits.pop()  # remove the last item form the list

'pear'

Another thing you might notice is that not all data can be sorted or compared. For instance, [None, 'hello', 10] doesn’t sort because integers can’t be compared to strings and None can’t be compared to other types. Also, there are some types that don’t have a defined ordering relation. For example, 3+4j < 5+7j isn’t a valid comparison.

## 3. Using Lists as Stacks

The list methods make it very easy to use a list as a stack, where the last element added is the first element retrieved (“last-in, first-out”). To add an item to the top of the stack, use append(). To retrieve an item from the top of the stack, use pop() without an explicit index. For example:

In [10]:
stack = [3, 4, 5]
stack.append(6)
stack.append(7)
stack

[3, 4, 5, 6, 7]

In [11]:
stack.pop()
stack

[3, 4, 5, 6]

In [12]:
stack.pop()
stack.pop()

stack

[3, 4]

## 4. Using Lists as Queues

It is also possible to use a list as a queue, where the first element added is the first element retrieved (“first-in, first-out”); however, lists are not efficient for this purpose. While appends and pops from the end of list are fast, doing inserts or pops from the beginning of a list is slow (because all of the other elements have to be shifted by one).

### To implement a queue, use collections.deque which was designed to have fast appends and pops from both ends. For example:

In [13]:
from collections import deque
queue = deque(["Eric", "John", "Michael"])
queue

deque(['Eric', 'John', 'Michael'])

In [14]:
queue.append("Terry")           # Terry arrives
queue

deque(['Eric', 'John', 'Michael', 'Terry'])

In [15]:
queue.append("Graham")          # Graham arrives
queue

deque(['Eric', 'John', 'Michael', 'Terry', 'Graham'])

In [16]:
queue.popleft()                 # The first to arrive now leaves

'Eric'

In [17]:
queue

deque(['John', 'Michael', 'Terry', 'Graham'])

In [18]:
queue.popleft()                 # The second to arrive now leaves

queue                           # Remaining queue in order of arrival

deque(['Michael', 'Terry', 'Graham'])

## 5. The 'del' statement

#### There is a way to remove an item from a list given its index instead of its value: the 'del' statement. 
#### This differs from the pop() method which returns a value. 
#### The 'del' statement can also be used to remove slices from a list or clear the entire list (which we did earlier by assignment of an empty list to the slice). For example:

In [19]:
a = [-1, 1, 66.25, 333, 333, 1234.5]
del a[0]
a

[1, 66.25, 333, 333, 1234.5]

In [20]:
del a[2:4]
a

[1, 66.25, 1234.5]

In [21]:
del a[:]
a

[]

'del' can also be used to delete entire variables:

In [22]:
del a  # Referencing the name 'a' hereafter is an error (at least until another value is assigned to it)
a

NameError: name 'a' is not defined

## 6. Tuples and Sequences

We saw that lists and strings have many common properties, such as indexing and slicing operations. Since Python is an evolving language, other sequence data types may be added. There is also another standard sequence data type: the tuple.

#### A tuple consists of a number of values separated by commas, for instance:

In [23]:
t = 12345, 54321, 'hello!'
t[0]

12345

In [24]:
t

(12345, 54321, 'hello!')

In [25]:
# Tuples may be nested:
u = t, (1, 2, 3, 4, 5)
u

((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))

In [26]:
# Tuples are immutable:
t[0] = 88888

TypeError: 'tuple' object does not support item assignment

In [27]:
# but they can contain mutable objects:
v = ([1, 2, 3], [3, 2, 1])
v

([1, 2, 3], [3, 2, 1])

Empty tuples are constructed by an empty pair of parentheses; a tuple with one item is constructed by following a value with a comma (it is not sufficient to enclose a single value in parentheses). Ugly, but effective. For example:

In [28]:
empty = ()
singleton = 'hello',    # <-- note trailing comma
len(empty)

0

In [29]:
singleton

('hello',)

The statement t = 12345, 54321, 'hello!' is an example of tuple packing: the values 12345, 54321 and 'hello!' are packed together in a tuple.

In [30]:
t = 12345, 54321, 'hello!'
t

(12345, 54321, 'hello!')

 The reverse operation is also possible:

In [32]:
x, y, z = t
print(x)
print(y)
print(z)

12345
54321
hello!


#### Sequence unpacking requires that there are as many variables on the left side of the equals sign as there are elements in the sequence.

## 7. Sets

Python also includes a data type for sets. A set is an unordered collection with no duplicate elements. Basic uses include membership testing and eliminating duplicate entries. Set objects also support mathematical operations like union, intersection, difference, and symmetric difference.

Curly braces or the set() function can be used to create sets. Note: to create an empty set you have to use set(), not {}; the latter creates an empty dictionary, a data structure that we discuss in the next section.

Here is a brief demonstration:

In [33]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)                      # show that duplicates have been removed

{'banana', 'apple', 'orange', 'pear'}


##### Alternativelly

In [35]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
basket = set(basket)
print(basket)             # show that duplicates have been removed

{'banana', 'apple', 'orange', 'pear'}


In [36]:
'orange' in basket                 # fast membership testing

True

In [37]:
'crabgrass' in basket

False

In [50]:
# Demonstrate set operations on unique letters from two words

a = set('abracadabra')
b = set('alacazam')
a                                  # unique letters in a

{'a', 'b', 'c', 'd', 'r'}

In [41]:
a - b                              # letters in a but not in b

{'b', 'd', 'r'}

In [42]:
a | b                              # letters in a or b or both

{'a', 'b', 'c', 'd', 'l', 'm', 'r', 'z'}

In [43]:
a & b                              # letters in both a and b

{'a', 'c'}

In [44]:
a ^ b                              # letters in a or b but not both

{'b', 'd', 'l', 'm', 'r', 'z'}

Similarly to list comprehensions, set comprehensions are also supported:

In [52]:
output = {x for x in a if x not in b}  # letters in a but not in b
output

{'b', 'd', 'r'}

## 8. Dictionaries

#### Another useful data type built into Python is the dictionary (see Mapping Types — dict). Dictionaries are sometimes found in other languages as “associative memories” or “associative arrays”. Unlike sequences, which are indexed by a range of numbers, dictionaries are indexed by keys, which can be any immutable type; strings and numbers can always be keys. 

#### It is best to think of a dictionary as a set of key: value pairs, with the requirement that the keys are unique (within one dictionary). A pair of braces creates an empty dictionary: {}. Placing a comma-separated list of key:value pairs within the braces adds initial key:value pairs to the dictionary; this is also the way dictionaries are written on output.

#### The main operations on a dictionary are storing a value with some key and extracting the value given the key. It is also possible to delete a key:value pair with del. If you store using a key that is already in use, the old value associated with that key is forgotten. It is an error to extract a value using a non-existent key.

#### Performing list(d) on a dictionary returns a list of all the keys used in the dictionary, in insertion order (if you want it sorted, just use sorted(d) instead). To check whether a single key is in the dictionary, use the in keyword.

#### Here is a small example using a dictionary:

In [54]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127
tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}

In [55]:
tel['jack']

4098

In [56]:
del tel['sape']
tel['irv'] = 4127
tel

{'jack': 4098, 'guido': 4127, 'irv': 4127}

In [57]:
list(tel)

['jack', 'guido', 'irv']

In [58]:
sorted(tel)

['guido', 'irv', 'jack']

In [59]:
'guido' in tel

True

In [60]:
'jack' not in tel

False

#### The dict() constructor builds dictionaries directly from sequences of key-value pairs:

In [61]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

#### In addition, dict comprehensions can be used to create dictionaries from arbitrary key and value expressions:

In [62]:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

#### When the keys are simple strings, it is sometimes easier to specify pairs using keyword arguments:

In [63]:
dict(sape=4139, guido=4127, jack=4098)

{'sape': 4139, 'guido': 4127, 'jack': 4098}